### ISSUE TITLE
Make changes to the FAQ

### ISSUE THREAD

**Issue by IDevelopAPI** [ru-python-beginners/faq#41]
Пожалуйста, внесите следующие изменения в README.md

1. Блок "Официальная документация", ссылка на Flask заменить на https://flask.palletsprojects.com/
2. Блок "Книги" - ссылка на E. Matthes. Learning Python / Э. Мэтиз. Изучаем Python более не актуальна

**Comment by leshark** [comment]
Спасибо, поправил
